update readme & debug deSPI-download and index

diff --git a/deSPI-download b/deSPI-download
--- a/deSPI-download
+++ b/deSPI-download
@@ -1,13 +1,14 @@
 #!/bin/bash
 # 
-#Author: Florian Breitwieser
-#Script: centrifuge-download
+#Original Author: Florian Breitwieser
+#Original Script: centrifuge-download
 #Site: https://github.com/infphilo/centrifuge/blob/master/centrifuge-download
 #Revised by Dengfeng Guan
 #Email: dfguan@hit.edu.cn
+#Please feel free to contact me if there are problems in the script 
 
 set -eu -o pipefail
-
+#set -x
 exists() {
   command -v "$1" >/dev/null 2>&1
 }
@@ -29,12 +30,23 @@ function download_n_process() {
     IFS=$'\t' read -r TAXID FILEPATH <<< "$1"
 
     NAME=`basename $FILEPATH .gz`
+	STOP_SIG="F"
+	# if file exist do nothing
+	# if gz file exist remove it first and redownload file and do the process
+	if [ ! -f "$LIBDIR/$DOMAIN/$NAME" ]
+	then
+			$DL_PROG "$LIBDIR/$DOMAIN/$NAME.gz" "$FILEPATH" || { printf "\nError downloading $FILEPATH!\n" >&2; STOP_SIG="T";}
+			if [ "$STOP_SIG" != "T" ]
+			then
+				gunzip -f "$LIBDIR/$DOMAIN/$NAME.gz" ||{ printf "\nError gunzipping $LIBDIR/$DOMAIN/$NAME.gz [ downloaded from $FILEPATH ]!\n" >&2;STOP_SIG="T";}
+			fi
+			if [ "$STOP_SIG" != "T" ]
+			then
+				echo "$LIBDIR/$DOMAIN/$NAME" "$TAXID" >> $LIBDIR/ref2tid.map
+			fi
 
-    [[ -f "$LIBDIR/$DOMAIN/$NAME.gz" ]] || $DL_PROG "$LIBDIR/$DOMAIN/$NAME.gz" "$FILEPATH" || { printf "\nError downloading $FILEPATH!\n" >&2 && exit 1; }
-    gunzip -f "$LIBDIR/$DOMAIN/$NAME.gz" ||{ printf "\nError gunzipping $LIBDIR/$DOMAIN/$NAME.gz [ downloaded from $FILEPATH ]!\n" >&2 &&  exit 255; }
-    #sed -i "s/^>/>tid|$TAXID|ref|/" $LIBDIR/$DOMAIN/$NAME
-  	echo $NAME $TAXID >>$LIBDIR/"$LIBDIR"_ref2tid.map 
-    echo done
+	fi
+	echo done
 }
 export -f download_n_process
 
@@ -112,7 +124,6 @@ WHEN USING database refseq OR genbank:
  -d <domain>            What domain to download. One or more of ${ALL_GENOMES} (comma separated, required).
  -a <assembly level>    Only download genomes with the specified assembly level ($ALL_ASSEMBLY_LEVELS). Default: '$ASSEMBLY_LEVEL'.
  -c <refseq category>   only download genomes the specified refseq category ($ALL_REFSEQ_CATEGORY).  Default: any.
- -g                     Download GI map.
 "
 
 # arguments: $OPTFIND (current index), $OPTARG (argument for option), $OPTERR (bash-specific)
@@ -137,7 +148,17 @@ shift $((OPTIND-1))
 [[ $# -eq 1 ]] || { printf "$USAGE" >&2 && exit 1; };
 DATABASE=$1
 
-echo $DATABASE
+#get absolute path
+CUR_DIR=$( pwd )
+if [ -d $BASE_DIR ]
+then
+	BASE_DIR=$( cd $BASE_DIR ; pwd ) 
+else
+	echo "$BASE_DIR is not a directory, Exit" >&2
+	exit 1
+fi
+
+#echo $DATABASE
 #### TAXONOMY DOWNLOAD
 FTP="ftp://ftp.ncbi.nih.gov"
 if [[ "$DATABASE" == "taxonomy" ]]; then 
@@ -207,13 +228,13 @@ for DOMAIN in $DOMAINS; do
 
     export DOMAIN=$DOMAIN
     check_or_mkdir_no_fail $LIBDIR/$DOMAIN
-
+	#echo $LIBDIR
     FULL_ASSEMBLY_SUMMARY_FILE="$LIBDIR/$DOMAIN/assembly_summary.txt"
     ASSEMBLY_SUMMARY_FILE="$LIBDIR/$DOMAIN/assembly_summary_filtered.txt"
 
     #echo "Downloading and filtering the assembly_summary.txt file ..." >&2
     $DL_PROG "$FULL_ASSEMBLY_SUMMARY_FILE" ftp://ftp.ncbi.nlm.nih.gov/genomes/$DATABASE/$DOMAIN/assembly_summary.txt > "$FULL_ASSEMBLY_SUMMARY_FILE"
-    echo $AWK_QUERY
+    #echo $AWK_QUERY
     awk -F "\t" "BEGIN {OFS=\"\t\"} $AWK_QUERY" "$FULL_ASSEMBLY_SUMMARY_FILE" > "$ASSEMBLY_SUMMARY_FILE"
 
     N_EXPECTED=`cat "$ASSEMBLY_SUMMARY_FILE" | wc -l`
diff --git a/deSPI-index b/deSPI-index
--- a/deSPI-index
+++ b/deSPI-index
@@ -1,20 +1,19 @@
 #!/bin/bash
-
-
-REFERENCE_LIB_PATH=$1
+#set -x 
+REFERENCE_PATH=$1
 KMER_SIZE=31
 TAXONOMY_TREE_PATH=$2
 DESPI_BIN_PATH=$3
 INDEX_DIR=$4
 
 USAGE="
-`basename $0` <REF_DIR> <NODE_PATH> <DESPI_BIN_DIR> <INDEX_DIR>
+`basename $0` <TID_REF_MAP> <NODE_PATH> <DESPI_BIN_DIR> <INDEX_DIR>
 
 ARGUMENT
-    <REF_DIR>                directory of reference library.
-    <NODE_PATH>              location of nodes.dmp file.
-    <DESPI_BIN_DIR>          directory of deSPI execuative files.
-    <INDEX_DIR>              directory to store deSPI's index.
+    <TID_REF_MAP>            ref2tid.map generated by deSPI-download.  				
+    <NODE_PATH>              path of nodes.dmp file.
+    <DESPI_BIN_DIR>          directory of deSPI's execuative files.
+    <INDEX_DIR>              directory used to store deSPI's index.
 "
 if [ $# -lt 4 ]
 then
@@ -23,74 +22,144 @@ then
 	exit 1
 fi
 
-check_for_jellyfish() {
-	
-	command -v jellyfish >/dev/null 2>&1 || return `false`
-
-	JELLYFISH_VERSION=$(jellyfish --version | awk '{print $2}')	
-         #echo $JELLYFISH_VERSION
-	if [[ $JELLYFISH_VERSION =~ ^1\. ]]
+check_for_jdbg() {
+	if [ -f "$DESPI_BIN_PATH"/jdbg ] && [ -f "$DESPI_BIN_PATH"/deSPI ]
 	then
 		return `true`
 	else
+		echo "ERROR: Program JDBG doesn't exist"
 		return `false`
 	fi	
 }
 
 TRANSIT=transit
+ABOREFPATH=.abo_ref_path
 
-
-if check_for_jellyfish
+if check_for_jdbg
 then
-	find $REFERENCE_LIB_PATH/ -name '*.fna' | xargs -n 1 cat > deSPI-wgs.fa
-	FILE_SIZE=$(ls -l deSPI-wgs.fa | awk '{print $5}')
-	#echo $FILE_SIZE		
-	let JELLYFISH_HASH_SIZE=FILE_SIZE*115/100
-	#echo $JELLYFISH_HASH_SIZE	
-	mkdir -p $INDEX_DIR
-	mkdir -p $TRANSIT 
-       	cd $TRANSIT
 
-	jellyfish count -m $KMER_SIZE -s $JELLYFISH_HASH_SIZE -t 4 ../deSPI-wgs.fa
-	
-	if [ -e "mer_counts_1" ]
+	if [ ! -f "$TAXONOMY_TREE_PATH" ]
 	then
-		#echo hahahha
-		jellyfish merge -o database.jdb.tmp mer_counts_*
-	else
-		mv mer_counts_0 database.jdb.tmp
+		echo "phelogentic tree missing error, please download it from NCBI"
+		exit 1
 	fi
-	mv database.jdb.tmp ../database.jdb
-
-	cd ..
-
-	rm -rf $TRANSIT
-
-
-	if [ -f "$DESPI_BIN_PATH/deSPI-sort" ]
+	if [ ! -f "$REFERENCE_PATH" ]
 	then
-		echo "sorting kmers......"
-		$DESPI_BIN_PATH/deSPI-sort database.jdb $KMER_SIZE >/dev/null 2>/dev/null
-		rm -f database.jdb
-	else
-		echo "deSPI-index requires deSPI-sort"
+		echo "Please specify the file contains path of reference and its taxonomy id"
 		exit 1
 	fi
 	
-	if [ -f "$DESPI_BIN_PATH/deSPI" ]
+	if [ ! -f "database.jdb" ]
 	then
-		echo "building deSPI index......"
-		$DESPI_BIN_PATH/deSPI index database.srt $TAXONOMY_TREE_PATH deSPI-wgs.fa $INDEX_DIR >/dev/null 2>/dev/null
-	else
-		echo "deSPI-index requires deSPI"
-	fi	
-	rm -f deSPI-wgs.fa database.srt
-	cp $TAXONOMY_TREE_PATH $INDEX_DIR/map
+		line=`head -n1 $REFERENCE_PATH | cut -f1`
+		
+		if [ ! "${line:0:1}" == "/" ]
+		then
+			cur_dir=$(pwd)
+			cd $(dirname $REFERENCE_PATH)
+			abs_path=$(pwd)
+			cd $cur_dir
+			sed "s#^#$abs_path&#g" $REFERENCE_PATH > $ABOREFPATH
+		else
+			cp $REFERENCE_PATH $ABOREFPATH 
+		fi	
+		
+		cut -f1 $ABOREFPATH |xargs ls -l >> ref_size
+		#cut -f1 $REFERENCE_PATH |xargs echo  
+		FILE_SIZE=$(awk 'BEGIN{size=0}{size += $5}END{print size}' ref_size)
+		#FILE_SIZE=$(ls -l deSPI-wgs.fa | awk '{print $5}')
+		#echo $FILE_SIZE		
+		rm -f ref_size
+		let JELLYFISH_HASH_SIZE=FILE_SIZE*115/100
+		#echo $JELLYFISH_HASH_SIZE	
+		if [ "$JELLYFISH_HASH_SIZE" -gt "2000000000" ]
+		then
+			JELLYFISH_HASH_SIZE="2000000000"
+		fi
+		
+		mkdir -p $INDEX_DIR
+		mkdir -p $TRANSIT 
+		cd $TRANSIT
+		#echo $DESPI_BIN_DIR
+		#echo $DESPI_BIN_PATH
+		
+		TRANSIT_DESPI_BIN_PATH=$DESPI_BIN_PATH
+		TRANSIT_TAXONOMY_TREE_PATH=$TAXONOMY_TREE_PATH
+		TRANSIT_REFERENCE_PATH=$ABOREFPATH
+		
+		if [ ! "${TRANSIT_DESPI_BIN_PATH:0:1}" == "/" ]
+		then
+			TRANSIT_DESPI_BIN_PATH="../$TRANSIT_DESPI_BIN_PATH"
+		fi	
+		
+		if [ ! "${TRANSIT_TAXONOMY_TREE_PATH:0:1}" == "/" ]
+		then
+			TRANSIT_TAXONOMY_TREE_PATH="../$TRANSIT_TAXONOMY_TREE_PATH"
+		fi	
+		if [ ! "${TRANSIT_REFERENCE_PATH:0:1}" == "/" ]
+		then
+			TRANSIT_REFERENCE_PATH="../$TRANSIT_REFERENCE_PATH"
+		fi	
+		
+		if [ ! -f database.jdb ]
+		then
+			if [ ! -f "mer_counts_0" ]
+			then
+				echo "generating kmers, hash size:$JELLYFISH_HASH_SIZE"
+				"$TRANSIT_DESPI_BIN_PATH"/jdbg count -m $KMER_SIZE -s $JELLYFISH_HASH_SIZE -t 4 -C -T $TRANSIT_TAXONOMY_TREE_PATH $TRANSIT_REFERENCE_PATH
+				rm -f $TRANSIT_REFERENCE_PATH
+			fi
+
+			if [ -e "mer_counts_1" ]
+			then
+				#echo hahahha
+				$TRANSIT_DESPI_BIN_PATH/jdbg merge -o database.jdb.tmp -T $TRANSIT_TAXONOMY_TREE_PATH mer_counts_* && touch .jf.merge
+			else
+				if [ -f "mer_counts_0" ]
+				then
+					mv mer_counts_0 database.jdb.tmp && touch .jf.merge
+				else
+					echo "Fail to use jdbg generate kmers"
+					exit 1
+				fi
+			fi
+			
+			if [ -f "database.jdb.tmp" ]
+			then	
+				mv database.jdb.tmp ../database.jdb && touch ../jdbg.complete && rm -f .jf.merge .jf.gen
+				echo "finish generating kmers"
+			else
+				echo "Fail to generate kmers"
+				exit 1
+			fi
+		fi
+		cd ..
+		rm -rf $TRANSIT
+	else 
+		echo "found database.jdb"		
+	fi
+	#if [ -f "$DESPI_BIN_PATH/deSPI-sort" ]
+	#then
+		#echo "sorting kmers......"
+		#$DESPI_BIN_PATH/deSPI-sort database.jdb $KMER_SIZE >/dev/null 2>/dev/null
+		#rm -f database.jdb
+	#else
+		#echo "deSPI-index requires deSPI-sort"
+		#exit 1
+	#fi
+	
+	echo "building deSPI index......"
+	if [ -f database.jdb ]
+	then
+		$DESPI_BIN_PATH/deSPI index database.jdb $TAXONOMY_TREE_PATH $REFERENCE_PATH $INDEX_DIR >/dev/null 2>/dev/null
+		$DESPI_BIN_DIR/convert2map	$TAXONOMY_TREE_PATH species > $INDEX_DIR/map
+	fi
+	rm -f database.srt ksp.srt
+	
 	echo "finished building deSPI index ^_^"
 else 
-	echo "deSPI requires jellyfish version 1"
+	echo "jdbg or deSPI missing error, re-download deSPI package to find"
 	exit 1
-
 fi	
 
 cd ..
